### ISSUE TITLE
Problem with train model on Zoo Animal Classification dataset from Kaggle

### ISSUE THREAD

**Issue by oleshch** [electricbrainio/electric-brain#33]
I was trying to train model using a Zoo Animal Classification dataset from Kaggle. I was able to uploaded the CSV and created the architecture. After that I tried to train a new model and it got stuck on the first iteration with no error message. 

Dataset: https://www.kaggle.com/uciml/zoo-animal-classification

**Comment by genixpro** [comment]
I believe we have fixed this issue. It seemed to be due to a bug where we didn't support column names that had symbols or spaces in them. This has been resolved by convertting said column names into machine names prior to generating code.
