### ISSUE TITLE
Cannot GET /app

### ISSUE THREAD

**Issue by DaShak** [electricbrainio/electric-brain#47]
On a stock Ubuntu 16 LTS server install, fully updated (apt-get upgrade)

https://twitter.com/KearnsTech/status/875545761462845442

Any advice?

**Comment by genixpro** [comment]
This is a bug - same as https://github.com/electricbrainio/electric-brain/issues/43. It should automatically redirect, for some reason it doesn't work without the extra slash. We will get on fixing this asap.

**Comment by genixpro** [comment]
We have made a fix for this issue, and will be releasing it this weekend. https://github.com/electricbrainio/electric-brain/commit/07537add8438ade4c1ab1cf84ae22bbd6da96ae8

**Comment by DaShak** [comment]
Thanks @genixpro - I read the other ticket, and now feel silly for overlooking that trailing slash - I have this app running at the https://Kearns.Tech/ office now!
![image](https://user-images.githubusercontent.com/1576844/27263633-a22f3fe4-543b-11e7-8dd3-16866f85cd3a.png)
